# Generated by Django 4.2.14 on 2024-07-30 18:36

import cloudinary.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, unique=True)),
                ('author', models.CharField(max_length=200)),
                ('category', models.IntegerField(choices=[(0, 'Literary fiction'), (1, 'Science fiction'), (2, 'Horror'), (3, 'Romance'), (4, 'Mystery'), (5, 'Fantasy'), (6, 'Poetry'), (7, 'Drama'), (8, 'Humor'), (9, 'History'), (10, 'Photography'), (11, 'Biography'), (12, 'Art'), (13, 'Travel'), (14, 'Other')], default=0)),
                ('pages', models.IntegerField()),
                ('image', cloudinary.models.CloudinaryField(default='imageplaceholder', max_length=255, verbose_name='image')),
                ('description', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('approved', models.BooleanField(default=False)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created_on'],
            },
        ),
    ]
